### I. Data Preparation (train)

The goal of this dataset is to clean the data set we'll use for data visualizations and training the model. Note that further data wrangling is required for training the model, which will be done in jupyter notebook no.2 from this project.
    
Here's what to expect on this notebook:
    - Importing libraries and data
    - Fixing data types
    - Find number of nulls
    - Feature engineering: Creating new columns, aggreagating categories and hot encoding
    
Finally we save modified data for future data visualizations

**a) Importing libraries and data**

In [1]:
# import libraries
import pandas as pd
from sklearn import preprocessing
import sklearn.model_selection as ms
from sklearn import linear_model
import sklearn.metrics as sklm
import numpy as np
import numpy.random as nr
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as ss
import math

%matplotlib inline
%matplotlib inline

In [2]:
#import data set
df=pd.read_csv('mower_market_snapshot.csv.csv',sep=';')
df.shape

(1399, 11)

In [3]:
#view data
df.head(5)

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.03551928211797,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.31809934886763,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.13731921134948,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.82946157588628,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.48693796090603,auto-portee,Medium,3ans.,0.007406,0.757614

**b) Fixing data types and see number of nulls**

In [4]:
#view data types and see if there's anything wrong
df.dtypes

capacity          float64
failure_rate      float64
id                  int64
margin            float64
price             float64
prod_cost          object
product_type       object
quality            object
warranty           object
market_share      float64
attractiveness    float64
dtype: object

**prod_cost** appears as an object when it should be a float.

In [5]:
#take action to convert prod_cost to numeric
df['prod_cost']=pd.to_numeric(df.prod_cost, errors='coerce')

In [6]:
#see if we did well
df.dtypes

capacity          float64
failure_rate      float64
id                  int64
margin            float64
price             float64
prod_cost         float64
product_type       object
quality            object
warranty           object
market_share      float64
attractiveness    float64
dtype: object

We did well, all data seem to be on the correct data type

In [7]:
#see how many nulls we have on data
df.isna().sum()

capacity           0
failure_rate       0
id                 0
margin             0
price              0
prod_cost         31
product_type       0
quality            0
warranty           0
market_share       0
attractiveness     0
dtype: int64

We'll have to deal with the 31 blanks on the product cost. Since we have 0 nulls on product margin and price, it should be easy to figure out.**Product cost = Price - Margin**

**c) Feature Engineering**

In [8]:
#drop margin column
df.drop(['prod_cost'],axis=1)

,capacity,failure_rate,id,margin,price,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,auto-portee,Medium,3ans.,0.007406,0.757614
5,19.548213,0.035428,18268,728.284617,905.297503,auto-portee,Medium,3 ans,0.007596,0.777051
6,12.242635,0.035492,18448,757.351286,930.615022,auto-portee,Hight,3_ans.,0.007488,0.766056
7,8.676314,0.042066,18943,633.515449,818.075591,auto-portee,Low,3 anss,0.005291,0.541318
8,15.264180,0.038804,19640,646.626567,816.774028,auto-portee,Low,3_ans.,0.006063,0.620278
9,16.190545,0.034045,19559,628.673360,814.799650,auto-portee,Low,3_ans.,0.005700,0.583117
10,14.028989,0.034757,19560,637.200636,785.615675,auto-portee,Low,3_anss,0.007457,0.762884
11,15.926414,0.037488,18922,675.328485,871.147948,auto-portee,Medium,3 anss,0.007248,0.741459
12,14.318660,0.037684,18858,648.838526,819.838099,auto-portee,Low,3_ans.,0.006919,0.707789
13,19.896179,0.040934,19307,690.403797,830.373642,auto-portee,Low,3 ans.,0.006047,0.618644
14,18.925359,0.029028,19177,709.668292,874.528101,auto-portee,Low,3 ans,0.006399,0.654611
15,0.014320,0.040453,19275,723.267667,932.020559,auto-portee,Medium,3_ans.,0.007492,0.766498
16,11.181391,0.039208,19478,684.847575,852.037497,auto-portee,Low,3 ans,0.006080,0.621991
17,22.824634,0.032932,18969,687.263834,848.527485,auto-portee,Medium,3 ans.,0.007811,0.799126
18,25.622312,0.038356,18965,697.112619,882.086532,auto-portee,Hight,3 anss,0.008584,0.878160
19,27.610500,0.041601,19376,658.273346,814.524030,auto-portee,Low,3 ans,0.006102,0.624247
20,18.043487,0.030080,19509,669.070606,827.985533,auto-portee,Low,3 anss,0.007235,0.740156
21,16.129713,0.040868,18361,658.161751,843.729983,auto-portee,Low,3 ans.,0.006234,0.637720
22,8.211970,0.034262,18977,650.040833,834.984548,auto-portee,Low,3_ans.,0.006442,0.659051
23,27.484897,0.035069,19257,638.986447,838.865752,auto-portee,Medium,3_anss,0.008572,0.876942
24,21.720148,0.035431,18495,679.310789,840.411156,auto-portee,Medium,3anss,0.007629,0.780437
25,20.231973,0.041615,18809,696.069144,845.858942,auto-portee,Low,3_ans.,0.006934,0.709330
26,20.928618,0.037014,19104,608.114727,752.739341,auto-portee,Low,3 ans.,0.005686,0.581701
27,17.062739,0.031948,18876,742.344491,891.334311,auto-portee,Hight,3 anss,0.008585,0.878246
28,21.792640,0.038328,18536,679.187622,846.329547,auto-portee,Low,3 ans,0.006936,0.709549
29,28.732437,0.031813,19031,781.467462,964.973926,auto-portee,Medium,3 ans,0.008001,0.818482
...,...,...,...,...,...,...,...,...,...,...
1369,49.590366,0.209080,18914,61.268302,72.496522,essence,Low,1_ans,0.001042,0.549627
1370,62.060763,0.194436,18340,66.834100,78.341434,essence,Medium,1_an.,0.001140,0.601384
1371,62.461930,0.221529,19036,65.802759,77.769715,essence,Low,1 an,0.001011,0.533320
1372,75.150330,0.204986,19552,59.759020,70.617876,essence,Low,1 an.,0.001564,0.825139
1373,69.419877,0.218645,18672,61.980466,863.736257,essence,Low,1_an,0.001267,0.668634
1374,58.825520,0.225132,18600,63.097488,73.263778,essence,Low,1_an.,0.001079,0.569230
1375,61.873397,0.259814,19586,59.586677,69.341855,essence,Hight,1_an,0.001620,0.854923
1376,62.157540,0.213768,18841,66.737623,76.887613,essence,Low,1 an.,0.001157,0.610553
1377,67.275887,0.209996,18313,65.066174,74.384568,essence,Low,1an.,0.000984,0.519148
1378,45.277486,0.221461,19165,65.747321,75.954893,essence,Low,1 an,0.000736,0.388462
1379,67.851696,0.223734,18274,66.168524,76.741522,essence,Medium,1an,0.001406,0.741746
1380,0.057506,0.249277,18787,62.634733,73.771107,essence,Low,1 an.,0.000950,0.501377
1381,64.606123,0.194852,19052,63.547025,74.546827,essence,Low,1 an.,0.001177,0.621001
1382,64.262408,0.232493,18880,65.147208,76.341530,essence,Low,1 ans,0.001178,0.621299
1383,49.677345,0.256845,18978,59.527243,70.053411,essence,Low,1ans,0.001342,0.708046
1384,55.503349,0.220019,19537,60.380859,71.381237,essence,Medium,1an,0.001314,0.693125
1385,65.996715,0.234680,19569,62.518795,73.461685,essence,Medium,1_an.,0.001568,0.827282
1386,50.341477,0.184653,18902,57.539868,68.267681,essence,Low,1 an,0.001340,0.706931
1387,0.056962,0.199166,18625,65.405507,74.762011,essence,Medium,1 an,0.001331,0.702132
1388,0.061640,0.213627,18279,65.331376,78.382424,essence,Low,1an.,0.000882,0.465321
1389,56.466095,0.247736,19182,58.301975,67.485880,essence,Low,1an,0.001333,0.703324
1390,50.359890,0.204743,18296,61.585886,72.714737,essence,Medium,1 an,0.001506,0.794333
1391,44.745485,0.210755,19187,64.430032,77.364718,essence,Hight,1_an,0.001006,0.530661
1392,61.018405,0.193229,18572,64.671915,76.931706,essence,Medium,1_an,0.001057,0.557520
1393,40.831294,0.217289,18950,62.296416,69.391858,essence,Low,1 an,0.001163,0.613849
1394,44.959895,0.234647,18451,63.662561,75.161102,essence,Medium,1 an,0.000973,0.513126
1395,59.356058,0.253694,18663,64.014543,75.395132,essence,Low,1ans,0.001038,0.547739
1396,67.865222,0.228935,19169,62.132035,810.883148,essence,Low,1an.,0.001243,0.655622
1397,66.855435,0.244948,18946,58.697122,68.491318,essence,Low,1 an,0.001644,0.867537
1398,54.712713,0.177143,19017,64.259212,74.955428,essence,Low,1an.,0.001022,0.538969

In [9]:
# Create again Prod_cost column by calculating it from existing columns.
df['prod_cost']=df['price']-df['margin']

In [10]:
# See if we did well (margin column should appear again on df)
df.head()

,capacity,failure_rate,id,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness
0,10.492623,0.042528,18377,633.766584,828.802103,195.035519,auto-portee,Low,3ans,0.006360,0.650648
1,20.273730,0.037896,19363,731.576817,882.894916,151.318099,auto-portee,Low,3 ans.,0.006840,0.699792
2,20.190457,0.039111,19641,741.218202,919.355522,178.137319,auto-portee,Low,3_ans,0.006179,0.632129
3,27.220131,0.041303,18728,654.255635,817.085097,162.829462,auto-portee,Low,3 anss,0.007925,0.810730
4,16.370911,0.037938,18722,703.094527,844.581465,141.486938,auto-portee,Medium,3ans.,0.007406,0.757614

In [11]:
#Verify we have no nulls
df.isna().sum()

capacity          0
failure_rate      0
id                0
margin            0
price             0
prod_cost         0
product_type      0
quality           0
warranty          0
market_share      0
attractiveness    0
dtype: int64

In [12]:
#Verify data set has the correct shape
df.shape

(1399, 11)

In [13]:
#Check if I have any Nan
df.isna().sum()

capacity          0
failure_rate      0
id                0
margin            0
price             0
prod_cost         0
product_type      0
quality           0
warranty          0
market_share      0
attractiveness    0
dtype: int64

In [14]:
#Find how many ID I have on the dataset, and how many values per country
df['id'].unique()

array([18377, 19363, 19641, ..., 19169, 18946, 19017])

In [15]:
#Ok, so I can delete ID column. 
df=df.drop(['id'],axis=1)

In [16]:
df.dtypes

capacity          float64
failure_rate      float64
margin            float64
price             float64
prod_cost         float64
product_type       object
quality            object
warranty           object
market_share      float64
attractiveness    float64
dtype: object

 Now I have to deal with **object** type data, namely non numerical data

* Fix Produt_type column

In [17]:
# Start with product_type
df['product_type'].value_counts()

essence        844
electrique     413
auto-portee    142
Name: product_type, dtype: int64

In [18]:
# Get dummy varibles for Product_type
df = pd.concat([df,pd.get_dummies(df['product_type'], prefix='product_type:')],axis=1)

In [19]:
#check new dummy columns have beenc created 
df.head(3)

,capacity,failure_rate,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness,product_type:_auto-portee,product_type:_electrique,product_type:_essence
0,10.492623,0.042528,633.766584,828.802103,195.035519,auto-portee,Low,3ans,0.006360,0.650648,1,0,0
1,20.273730,0.037896,731.576817,882.894916,151.318099,auto-portee,Low,3 ans.,0.006840,0.699792,1,0,0
2,20.190457,0.039111,741.218202,919.355522,178.137319,auto-portee,Low,3_ans,0.006179,0.632129,1,0,0

* Fix Quality column

In [20]:
#Check quality column
df['quality'].value_counts()

Low       971
Medium    295
Hight     133
Name: quality, dtype: int64

There is a misspelling on the high category, as it's written 'Hight' where it should be "High". So I proceed to fix it. Also, for comercial purposes, I think it's better to use the word 'Basic' instead of 'Low', so I proceed to undertake this change as well.

In [21]:
# quality column misspelling correction
quality_cat = {'Low':'Basic', 
                'Medium':'Medium',
                'Hight':'High'}
df['quality']=[quality_cat[x] for x in df['quality']]
df['quality'].value_counts()

Basic     971
Medium    295
High      133
Name: quality, dtype: int64

In [22]:
# Get dummy varibles for Quality
df = pd.concat([df,pd.get_dummies(df['quality'], prefix='Quality:')],axis=1)

In [23]:
#check new dummy columns have been created 
df.head(3)

,capacity,failure_rate,margin,price,prod_cost,product_type,quality,warranty,market_share,attractiveness,product_type:_auto-portee,product_type:_electrique,product_type:_essence,Quality:_Basic,Quality:_High,Quality:_Medium
0,10.492623,0.042528,633.766584,828.802103,195.035519,auto-portee,Basic,3ans,0.006360,0.650648,1,0,0,1,0,0
1,20.273730,0.037896,731.576817,882.894916,151.318099,auto-portee,Basic,3 ans.,0.006840,0.699792,1,0,0,1,0,0
2,20.190457,0.039111,741.218202,919.355522,178.137319,auto-portee,Basic,3_ans,0.006179,0.632129,1,0,0,1,0,0

* Fix Warranty colum

In [24]:
# Check waranty column
df['warranty'].value_counts()

1 an.     103
1 an      101
1_ans      96
1_an.      95
1an        94
1ans       94
1_an       91
1 ans      86
1an.       84
2ans.      54
2 anss     52
2_anss     51
2 ans      48
2 ans.     45
2_ans      43
2ans       42
2_ans.     41
2anss      37
3 ans      21
3 anss     21
3_ans.     19
3ans       17
3_ans      14
3 ans.     14
3_anss     12
3anss      12
3ans.      12
Name: warranty, dtype: int64

There are basically 3 categories in this columns, but each category has many different entries. I shall aggregate categories, so that there's only 3 left.

In [25]:
# aggregate categories warranty column
warranty_cat = {'1 an.':'1',
                '1 an':'1',
                '1_ans':'1',
                '1_an.':'1',
                '1ans':'1',
                '1an':'1',
                '1_an':'1',
                '1 ans':'1',
                '1an.':'1', 
                '2ans.':'2',
                '2 anss':'2',
                '2_anss':'2',
                '2_anss':'2',
                '2 ans':'2', 
                '2 ans.':'2',
                '2_ans':'2',
                '2ans':'2', 
                '2_ans.':'2', 
                '2anss':'2',
                '3 ans':'3','3 anss':'3','3_ans.':'3','3ans':'3','3_ans':'3','3 ans.':'3','3anss':'3','3_anss':'3','3ans.':'3'}
df['warranty']=[warranty_cat[x] for x in df['warranty']]
df['warranty'].value_counts()

1    844
2    413
3    142
Name: warranty, dtype: int64

In [26]:
# Get dummy varibles for Warranty
df = pd.concat([df,pd.get_dummies(df['warranty'], prefix='Warranty_years:')],axis=1)

* I create a brand **new column**: % of Margin

In [27]:
df['Perc_margin']=(df['margin']/df['prod_cost'])*100

In [28]:
df['Perc_margin'].describe()

count    1399.000000
mean      433.920577
std       191.163173
min      -266.413089
25%       252.006757
50%       504.043774
75%       578.291734
max       877.977874
Name: Perc_margin, dtype: float64

In [29]:
# I shall turn this column from numerical into categorical
def Perc_margin_xform(al):
    if al < 0: return 'negtive'
    elif al <252: return 'Low'
    elif al <504: return 'Medium'
    else: return 'High'

df["Perc_margin"] = df['Perc_margin'].map(Perc_margin_xform)


df['Perc_margin'].value_counts()

High       700
Medium     349
Low        333
negtive     17
Name: Perc_margin, dtype: int64

In [30]:
# Get dummy varibles for Quality
df = pd.concat([df,pd.get_dummies(df['Perc_margin'], prefix='Perc_Margin:')],axis=1)

* Move label to the end of dataset

In [31]:
#Move LABEL column (attractiveness) to the end of the dataset
cols = [col for col in df if col != 'attractiveness']+['attractiveness']
df = df[cols]
df.head()

,capacity,failure_rate,margin,price,prod_cost,product_type,quality,warranty,market_share,product_type:_auto-portee,...,Quality:_Medium,Warranty_years:_1,Warranty_years:_2,Warranty_years:_3,Perc_margin,Perc_Margin:_High,Perc_Margin:_Low,Perc_Margin:_Medium,Perc_Margin:_negtive,attractiveness
0,10.492623,0.042528,633.766584,828.802103,195.035519,auto-portee,Basic,3,0.006360,1,...,0,0,0,1,Medium,0,0,1,0,0.650648
1,20.273730,0.037896,731.576817,882.894916,151.318099,auto-portee,Basic,3,0.006840,1,...,0,0,0,1,Medium,0,0,1,0,0.699792
2,20.190457,0.039111,741.218202,919.355522,178.137319,auto-portee,Basic,3,0.006179,1,...,0,0,0,1,Medium,0,0,1,0,0.632129
3,27.220131,0.041303,654.255635,817.085097,162.829462,auto-portee,Basic,3,0.007925,1,...,0,0,0,1,Medium,0,0,1,0,0.810730
4,16.370911,0.037938,703.094527,844.581465,141.486938,auto-portee,Medium,3,0.007406,1,...,1,0,0,1,Medium,0,0,1,0,0.757614

Now dataset is ready for visualizations and data wrangling

In [32]:
#export data set to main directory to be used in a different jupyter notebook
df.to_csv("dfprepared.csv", index=False)